repos:
  - repo: https://github.com/ambv/black
    rev: 23.7.0  # TODO: update version
    hooks:
    - id: black
      language_version: python3
      exclude: (geordpy/_version|versioneer).py

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # TODO: update version
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: (geordpy/_version|versioneer).py

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # TODO: update version
    hooks:
    - id: flake8
