name: Get coverage

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read
      id-token: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install package
        run: |
          pip install -e .[dev]

      - name: Run test suite
        run: |
          set -o pipefail
          pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov=geordpy \
          | tee pytest-coverage.txt

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./pytest-coverage.txt

      - name: Add Coverage to pull request
        uses: MishaKav/pytest-coverage-comment@v1.1.48
        if: github.event_name == 'pull_request'
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
